sudo: required
services:
  - docker

before_install:
  - docker build -t plat123456789/docker-react -f Dockerfile.dev .

  script:
    - docker run plat123456789/docker-react npm run test -- --coverage
